### ISSUE TITLE
[Feature Request] Use MySQL/Bungee plugin or more to support switch server remember if enabled

### ISSUE THREAD

**Issue by ghost** [JEFF-Media-GbR/Spigot-BestTools#23]
Use MySQL/Bungee plugin or more to support switch server remember if enabled

**Comment by mfnalex** [comment]
BestTools uses the player's PDC which should be shared across servers automatically. What server software are you using?

**Comment by ghost** [comment]
OK...

**Comment by ghost** [comment]
> BestTools uses the player's PDC which should be shared across servers automatically. What server software are you using?

I use HuskSync to sync, but the data is not shared

**Comment by mfnalex** [comment]
Please note all my plugins are Spigot plugins. If you want to sync stuff between servers, then this is the job of your sync plugin.

If HuskSync doesn't sync the PDC, then you should request them to add an option for this. Because in my opinion, the PDC belongs to a player exactly as other NBT tags like health, inventory, or potion effects do.

IMHO HuskSync should sync stuff between servers like vanilla does between worlds, and that's EVERY NBT tag, including the "BukkitValues" (PDC) one.

**Comment by ghost** [comment]
> Please note all my plugins are Spigot plugins. If you want to sync stuff between servers, then this is the job of your sync plugin.
> 
> If HuskSync doesn't sync the PDC, then you should request them to add an option for this. Because in my opinion, the PDC belongs to a player exactly as other NBT tags like health, inventory, or potion effects do.
> 
> IMHO HuskSync should sync stuff between servers like vanilla does between worlds, and that's EVERY NBT tag, including the "BukkitValues" (PDC) one.

seems HuskSync can sync PDC, but still can't sync this plugin's data cross servers

**Comment by mfnalex** [comment]
It currently only syncs PDC for ItemMeta, but the HuskSync dev added it to the todo list now: https://github.com/WiIIiam278/HuskSync/issues/30

**Comment by ghost** [comment]
> It currently only syncs PDC for ItemMeta, but the HuskSync dev added it to the todo list now: [WiIIiam278/HuskSync#30](https://github.com/WiIIiam278/HuskSync/issues/30)

Well sorry it's my fault, I used to think HuskSync could sync PDC
